Sprint 1/step 2
L13912/yap_burger pull request #1
Opened 2021-11-19 13:59 UTC by L13912

R1

2021-11-19 14:41 UTC, grishbar commented
Привет, для начала обрати внимание на макет, у тебя должен быть горизонтальный скролл справа в burger-constructor, и слева в burger-ingredients.
Также сверху должна быть только одна активная ссылка (смотри скрин с дизайна)
Также при клике на табы "булки", "соусы", "начинки" твой компонент должен проскроливаться до этой категории, и соответственно таб становится активным. Также при обычном скролле burgeringredients активный таб меняется при доскролле до определенной категории
<img width="584" alt="Screen Shot 2021-11-19 at 17 37 10" src="https://user-images.githubusercontent.com/32193933/142640252-4a7a119a-0821-4442-957e-eeb0734a3df3.png">
<img width="584" alt="Screen Shot 2021-11-19 at 17 37 57" src="https://user-images.githubusercontent.com/32193933/142640373-296ae581-4000-4b21-b8b2-6d55b0e1e9d3.png">
<img width="589" alt="Screen Shot 2021-11-19 at 17 39 10" src="https://user-images.githubusercontent.com/32193933/142640551-84c0c6d0-8ab1-492b-8ef6-21893574fd97.png">

2021-11-19 15:17 UTC, grishbar commented
`надо исправить` также у твоих булок должны быть подписи "вверх" и "низ", добавь их
<img width="766" alt="Screen Shot 2021-11-19 at 18 17 43" src="https://user-images.githubusercontent.com/32193933/142646464-164b4afd-3608-4688-9ab6-ca7541c97cd7.png">

2021-11-19 15:55 UTC, grishbar requested changes
Молодец, проделано много работы, проект почти готов, мне понравилось твое решение с выносом классов для элементов в компонент из верстки но не заигрывайся с этим, круто, что все сделала на функциональных компонентах и деструктурировала везде пропсы, есть несколько замечаний, которые надо исправить до принятия работы:

- [x] Доработать весь проект, сделать его согласно макету 
- [x] Переименовать все плохо названные переменные, каждая переменная должна быть названа так, что не заглядывая, что в ней лежит, ты примерно могла представить за что эта переменная отвечает.
- [ ] Если в качестве пропсов передается объект или массив объектов, то в propTypes описана структура этого объекта
- [ ] Удалить ненужный код, которой ничего по факту не делает
- [ ] Надо корректно реализовать подписку и отписку на событие закрытия моталки при клике на клавишу Esc
- [ ] Вынести из компонента функци которые не требует регулярного обновления
- [ ] Переделать полностью запрос за ингредиентами он не должен содержать лишнего кода и должен выполняться один раз на странице, в useEffect

2021-11-19 15:55 UTC, grishbar commented on src/App.jsx
> +    })
`надо исправить` такие состояния компонента нужно разделять, во первых это разные абстракции поэтому семантически так будет более корректно, во вторых если у тебя будет меняться хоть одно из этих полей, то будет перерендываться все поля с ними связаными а не только измененные, что не очень, теряешь сильно в производительности

2021-11-19 15:55 UTC, grishbar commented on src/App.jsx
> +        doRequest()
`надо исправить` имя doRequest нам ни о чем не говорит, надо переделать на getIngredients или что нибудь типо такого, имя переменно должно нам явно говорить об ее предназначении

2021-11-19 15:55 UTC, grishbar commented on src/App.jsx
> +        data: []
`надо исправить` имя дата не несет никакого смысла, тут у тебя будут лежать ингредиенты, назови эту переменную соответственно

2021-11-19 15:55 UTC, grishbar commented on src/App.jsx
> +    const contentStyles = `${styles.content}`;
`можно лучше` круто, что вынесла классы из верстки, но все таки это не styles а классы, переименуй переменные и тут

2021-11-19 15:55 UTC, grishbar commented on src/app.module.css
> +* { margin: 0; padding: 0; }
`можно лучше` глобальные стили, надо описывать в index.css и убирать у всех элементов марджины и паддинги неправильно, есть тэги p, li и другие у которых дефолтные значение очень удобные, а если надо, то ты без проблем их поменяешь отдельно для каждого элемент

2021-11-19 15:55 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.jsx
> +        data: PropTypes.array
`надо исправить` надо описать какие элементы будут лежать в твоем массиве

2021-11-19 15:55 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.jsx
> +    const [isOn, setOn] = useState(false);
`надо исправить` тоже очень плохие названия переменных, isModalOpen setIsModalOpen уже будет намного лучше

2021-11-19 15:55 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.jsx
> +    }
`надо исправить` `const items = [...data]`
а вобще можешь сразу пользоваться data, зачем ты перекладываешь непонятно, выглядит как излишнее действие
также навания items и data очень плохие надо переименовать

2021-11-19 15:55 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.jsx
> +                    </Portal>
`надо исправить` неправильная реализация портала, прочитай еще раз про него внимательней, и перенеси логику портала в компонент Modal

2021-11-19 15:55 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.jsx
> +        data: PropTypes.array
`надо исправить` тут также надо описать структуру этого массива

2021-11-19 15:55 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    const [current, setCurrent] = React.useState('Булки')
`надо исправить` плохое название, currentActiveCategory или что нибудь такое должно быть

2021-11-19 15:55 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    sortData(data);
`можно лучше` так ок, но можно сделать в три строчки будет читаться напорядок проще 
```
const buns = data.filter(item => item.type === 'bun');
...
```

2021-11-19 15:55 UTC, grishbar commented on src/components/ingredient-card/ingredient-card.jsx
> +        card: PropTypes.object
`надо исправить` надо описать структуру объекта

2021-11-19 15:55 UTC, grishbar commented on src/components/ingredient-card/ingredient-card.jsx
> +    const [isOn, setOn] = useState(false);
`надо исправить` плохие названия

2021-11-19 15:55 UTC, grishbar commented on src/components/ingredient-details/ingredient-details.jsx
> +        card: PropTypes.object
`надо исправить` надо описать структуру ответа

2021-11-19 15:55 UTC, grishbar commented on src/components/ingredient-details/ingredient-details.jsx
> +    const value = `pt-1  text text_type_digits-default ${styles.navy}`;
`надо исправить` это все прикольно, что ты все классы выносишь в компонент, но нужно их все корректно одинаково называть по одному паттерну к примеру *Class
и на самом деле выносить не динамические классы особой пользы не несет, только затрудняет чтение

2021-11-19 15:55 UTC, grishbar commented on src/components/modal-overlay/modal-overlay.js
> +    let closeModal = () => {};
`надо испрвить` это const и подобные функции которые ни от чего не зависят надо выносить из компонента, чтобы они не перерасчитывались при каждой перерисовке

2021-11-19 15:55 UTC, grishbar commented on src/components/modal-overlay/modal-overlay.js
> +    }
`надо исправить` будешь при каждом ререндере навешивать новый eventListener , сделай при помощи useEffect и не зубдь добавить отписку от события

2021-11-19 15:55 UTC, grishbar commented on src/utils/create-portal.js
> +export default Portal;
`надо исправить` все это должно быть в компоненте modal

2021-11-19 15:55 UTC, grishbar commented on src/utils/doRequest.js
> +            "proteins":44,
`надо исправить` ненужные комментарии должны быть удалены

2021-11-19 15:55 UTC, grishbar commented on src/utils/doRequest.js
> +const data  = 'https://norma.nomoreparties.space/api/ingredients';
`надо исправить` надо переименовать переменную, + такие константные переменные принято называть в SNAKE_CASE так, что у тебя должно быть что то типа: INGREDIENTS_URL

2021-11-19 15:55 UTC, grishbar commented on src/utils/doRequest.js
> +    if (typeof data != 'string')
`надо исправить` это бессмысленная проверка, ты сама сверху задала эту константую переменную, и сразу проверять ее как то странно

2021-11-19 15:55 UTC, grishbar commented on src/utils/doRequest.js
> +
`надо исправить` это все выглядит жутко некрасиво и очень много лишних действий почитай вот [здесь](https://learn.javascript.ru/fetch) поподробней как работать с сетью и посмотри на примеры

2021-11-20 08:27 UTC, L13912 commented on src/App.jsx
> +    })
исправила

2021-11-20 08:27 UTC, L13912 commented on src/App.jsx
> +        doRequest()
исправила

2021-11-20 08:27 UTC, L13912 commented on src/App.jsx
> +        data: []
исправила

2021-11-20 08:27 UTC, L13912 commented on src/App.jsx
> +    const contentStyles = `${styles.content}`;
исправила

2021-11-20 08:29 UTC, L13912 commented on src/app.module.css
> +* { margin: 0; padding: 0; }
Перенесла в index, не согласна с запретом на обнуление. У нас своя система отступов, обязательная, нативные все равно придется отменить везде. Это увеличит количество бессмысленного кода в приложении.

2021-11-20 08:34 UTC, L13912 commented on src/utils/doRequest.js
> +            "proteins":44,
исправила

2021-11-20 08:34 UTC, L13912 commented on src/utils/doRequest.js
> +const data  = 'https://norma.nomoreparties.space/api/ingredients';
исправила

2021-11-20 08:37 UTC, L13912 commented on src/utils/doRequest.js
> +    if (typeof data != 'string')
У вас часто падает сервер, чтоб не зависеть от него,  я в эту же функцию подаю замоканные данные, а они идут сразу объектом, и возвращаются как есть. И комментарий выше из-за этого же висел

2021-11-20 09:09 UTC, L13912 commented on src/utils/doRequest.js
> +
1. Если в ответе не json, response.json возвращает parse error, вместо ошибки сервера.
2. Чтобы получить корректный текст ошибки, мы сначала считываем текст, а затем пробуем его распарсить. 
3. Если сервер не смог обработать запрос, то ответить может роутер, провайдер. например, ошибка 502, 504, 503 и тп. В этом случае у нас в  message окажется полный текст ошибки.

2021-11-20 10:35 UTC, L13912 commented on src/utils/create-portal.js
> +export default Portal;
исправила

2021-11-20 10:42 UTC, L13912 commented on src/utils/doRequest.js
> +
Выполняется он всего 1 раз, в useEffect, в App.jsx
Далее все компоненты работают с сохраненными данными:
```
    useEffect(() => {
        getIngredients()
            .then(res => {
                setIngredients({ingredientsData: res.data})
            })
            .catch(err => {
                setState({...state, error: err})
            });
    }, []);
```

2021-11-20 10:45 UTC, L13912 commented
По работе табов и скроллировании до активной вкладки  - уточните ТЗ - этого нет в задании на 1 спринт.

2021-11-21 02:42 UTC, grishbar requested changes
Большую часть проблем исправила, это хорошо, осталось еще чуть чуть доделать:

- [ ] Надо корректно реализовать подписку и отписку на событие закрытия моталки при клике на клавишу Esc
- [ ] Исправить логику закрытия компонента при клике на overlay

Насчет табов действительно в тз не сказано, так, что реализовывать или нет их логику это на твое усмотрение

2021-11-21 02:42 UTC, grishbar commented on src/App.jsx
> +    })
`можно лучше` это тоже вполне читаемо, и не будет вызывать большого количества лишних перерисовок, но все таки лучше если есть возможность всегда разделять объекты состояния

2021-11-21 02:42 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.jsx
> +    const [isOn, setOn] = useState(false);
`можно лучше` давай эти переменные тоже переименуем все таки

2021-11-21 02:42 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.jsx
> +    const totalCont = `mr-10 ${styles.totalCont}`;
`можно лучше` в app-header все классы назвала *Classes , а тут нет, нужно стараться выдерживать один стиль на протяжение всего проекта, так твой код становится напорядок читаемей

2021-11-21 02:42 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.jsx
> +    }
`надо исправить` 
```
const items = ingredients.slice(1);
```

2021-11-21 02:42 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.jsx
> +                }
`можно лучше` проверка на items излишняя, items всегда возвращает true, не будет случая когда этот див не отрисуется, если пока там нет элементов не хочешь рисовать этот див контейнер, то сделай проверку на Boolean(items.length)

2021-11-21 02:42 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.module.css
> +}
`можно лучше` пустых css стилей не должно быть в проекте

2021-11-21 02:42 UTC, grishbar commented on src/components/modal-overlay/modal-overlay.jsx
> +    let closeModal = () => {};
`надо исправить`  сразу положи в эту переменную то, что хочешь положить в нее useEffect и кажется вся эта логика тут излишняя, если удалишь строчки с 12 по 21 и в 25 положишь просто close, то все будет работать точно также

2021-11-21 02:42 UTC, grishbar commented on src/components/modal-overlay/modal-overlay.jsx
> +    }
`надо исправить` ранее указывал, что надо переделать подписку на события, если не совсем понятно как это должно выглядить, то должно быть что то такое:
```
const handleEscCloseModals = (e) => {
    if (e.key === 'Escape') close();
}
  React.useEffect(() => {
    document.addEventListener("keydown", handleEscCloseModals);
    return () => {
      document.removeEventListener("keydown", handleEscCloseModals);
    };
  }, []);

```
и эта логика должны быть в компоненте modal

2021-11-21 02:42 UTC, grishbar commented on src/utils/getIngredients.js
> +}
`надо исправить` как ранее писал выполняешь лишние действия, если хочешь, чтобы при каких либо ошибок с сетью использовались замоканные данные, то и надо так код описать а не менять вручную каждый раз, ты же программист все таки)
```
async function getIngredients() {
   const ingredientsData = await fetch(`${INGREDIENTS_URL}`)
    .then(res => {
      return res.json()
    }).then (res => {
     return res.data;
    }).catch(err => {
      console.log(err)
      return ingredientsDataMock;
    })
    return ingredientsData;
}

```
надеюсь, теперь стало понятно какие действия выполняешь лишние и как можно красиво написать, тут можно спокойно async await удалить, возвращать и работать с промисом, так было бы идеально, но тут, чтобы было понятно сделал в твоем стиле с acync/await

2021-11-21 10:45 UTC, L13912 commented on src/components/burger-constructor/burger-constructor.jsx
> +    }
исправлено

2021-11-21 10:45 UTC, L13912 commented on src/components/burger-constructor/burger-constructor.jsx
> +                }
исправлено, это с отладки пропсов забыла

2021-11-21 10:47 UTC, L13912 commented on src/components/burger-ingredients/burger-ingredients.module.css
> +}
исправлено

2021-11-21 11:14 UTC, L13912 commented on src/components/modal-overlay/modal-overlay.jsx
> +    }
исправлено

2021-11-21 11:15 UTC, L13912 commented on src/components/modal-overlay/modal-overlay.jsx
> +    let closeModal = () => {};
исправлено

2021-11-21 11:54 UTC, L13912 commented on src/components/burger-constructor/burger-constructor.jsx
> +    const [isOn, setOn] = useState(false);
исправила

2021-11-21 12:00 UTC, L13912 commented on src/utils/getIngredients.js
> +}
Смотрите, специально послала запрос на некорректный адрес, вот разница:
Вот ответ с моего запроса, все тело неудачного запроса в message, не думаю, что на этом учебном проекте это важно, но вообще бывает. + доступны все поля res. 
<img width="1324" alt="Снимок экрана 2021-11-21 в 14 23 06" src="https://user-images.githubusercontent.com/16000373/142760174-6cc985ce-a412-46d0-be3e-15e6d96de2b2.png">

Вот ответ вашего запроса: кроме кода ошибки мы ничего не знаем.  
<img width="1393" alt="Снимок экрана 2021-11-21 в 14 25 43" src="https://user-images.githubusercontent.com/16000373/142760221-564f798f-78dc-4b98-8e6d-f204150c65dd.png">


Проверку на строку убрала, чтоб она вам не мешала.

2021-11-22 00:08 UTC, grishbar commented
Отлично, все критичные ошибки исправила, работу засчитываю, насчет запроса, мне не нравится, что у тебя логика обработки json в объект зачем то вынесена в отдельную функцию, когда это делается в одну строчку response.json() + лишнее действие на 14 строчке это вызов метода text(), + ты зачем то самостоятельно if обрабатываешь ошибку, когда ошибка обрабатывается блоком catch, там предусмотрены все возможные проблемы которые у тебя могут произойти с запросом + ты смотришь, что статус ошибки больше 400, это тоже ок, но тебе, чтобы все работало интересуют исключительно 2xx статусы соответственно надо смотреть на [response.ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)
Ошибку можешь обработать как хочешь в моем примере она отличается от твоего без сокрального смысла, я просто так написал, можешь записывать все тело неудачного запроса это на твое усмотрение.
В целом работа отличная, хорошо, что имеешь свое мнение на счет тех или иных вопросов по коду, ревью это всегда обоюдный процесс и ревьюер тоже может ошибиться, хочется чтобы ты переделала все таки поход за данными на мой пример, или на свой аналогичный.
Удачи в дальнейшем обучении)

2021-11-22 09:44 UTC, merged